version: '3.8'

networks:
  devcloud:
    name: 'devcloud_network'

volumes:
  cache:
    driver: local

services:
  postgres:
    image: postgres
    container_name: devcloud_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devcloud
    networks:
      - 'devcloud'
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgres/init:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: devcloud_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - 'devcloud'
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: devcloud_kafka
    depends_on:
      - zookeeper
    networks:
      - 'devcloud'
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  scheduler:
    image: ghcr.io/asyncomatic/scheduler:1.0
    container_name: devcloud_scheduler
    networks:
      - "devcloud"
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLIENT_ID: devcloud
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devcloud
